### PR TITLE
Fix auto-detection for legacy and classic bot tokens

### PR DESCRIPTION
**Pull request by nzlosh**
This patch addresses incorrectly detecting legacy tokens for use with the RTM API.

### CODE REVIEW

**Comment by ostefano** [comment]
@nzlosh note that this doesn't work as-is. See https://github.com/nzlosh/err-backend-slackv3/pull/11

**Comment by nzlosh** [comment]
That's strange, I don't see `apps` mentioned in the Slack documentation https://api.slack.com/scopes.  How did you find this scope?

**Comment by ostefano** [comment]
Just printed the full list of scopes I receive when a connection is attempted since the fix wasn't being applied.

**Comment by nzlosh** [comment]
That's a bit of a concern.  If the Slack documentation is incomplete, there's no guarantee all possible legacy/classic bot scopes are being tested for.  I'll try find an exhaustive list online.  Thanks for pointing that out.

**Pull request merged**
